### ISSUE TITLE
Does drawXBMP function available in ucglib?

### ISSUE THREAD

**Issue by venkatesh223** [olikraus/Ucglib_Arduino#16]
Does ucglib support drawxbmp like the U8g2 library?
If no can you help me with an alternative on how to display an image using ucglib arduino please.

**Comment by olikraus** [comment]
I once created an example to show a pic in TGA format (https://en.wikipedia.org/wiki/Truevision_TGA): https://github.com/olikraus/ucglib/blob/master/sys/arduino/ShowTGA/ShowTGA.ino

**Comment by venkatesh223** [comment]
This requires an SD Card to store tga file.
Anything with bitmap or with xbm file?

**Comment by olikraus** [comment]
> This requires an SD Card to store tga file.

Obviously. But you can just use XBM instead. Will need a decoding of the XBM format, but this shouldn't be a big problem.

**Comment by venkatesh223** [comment]
Yea will try.
Thanks for the support.
