### ISSUE TITLE
Ucglib tried on ST7789v need hep with that

### ISSUE THREAD

**Issue by venkatesh223** [olikraus/Ucglib_Arduino#18]
Hello Olikraus,
I tried this library using a 2"inch 240X320 LCD driven by ST7789v the results were as shown in the image and video.
In the library i used ST7735 and connected this display.
To make it work proper will changing the resolution in all the respective files work? Or anything else needed to be done? Please help.

https://drive.google.com/open?id=1SYzbJIDt8TSCOI7K0Pri1pekVdHPPiMs

Will be waiting for your reply.
Regards 
Venkatesh
![IMG_20190716_100108](https://user-images.githubusercontent.com/49774173/61266782-036d7380-a7b3-11e9-8bdf-19b2f4dfd4b9.jpg)

**Comment by olikraus** [comment]
hmmm... difficult. I do not work on this project any more... and it is long time back...

**Comment by venkatesh223** [comment]
Thank you for your reply.
So any suggestions on what can be done briefly.
I shall try it.

**Comment by venkatesh223** [comment]
Hello there,
Huge thanks for the library,
as you know i was working with ST7789v driven display using your library.
its working finally. After many changes
Huge thanks again for the library.
![IMG_20190719_124855](https://user-images.githubusercontent.com/49774173/61517169-3bc7b880-aa24-11e9-8b45-8d2d6d89ca3e.jpg)

**Comment by olikraus** [comment]
wow

**Comment by xmenxwk** [comment]
what changes have you made ?

**Comment by charleslemaire0** [comment]
I am interested too
